// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import "fyne.io/fyne/v2"

var resourceRedcubeiconSvg = &fyne.StaticResource{
	StaticName: "red_cube_icon.svg",
	StaticContent: []byte(
		"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg width=\"64\" height=\"64\" viewBox=\"0 0 64 64\" xmlns=\"http://www.w3.org/2000/svg\">\n  <!-- Фон -->\n  <rect width=\"64\" height=\"64\" fill=\"#2b2b2b\" rx=\"8\"/>\n  \n  <!-- Красный куб - передняя грань -->\n  <rect x=\"16\" y=\"32\" width=\"24\" height=\"24\" fill=\"#ff4444\" stroke=\"#cc3333\" stroke-width=\"1\"/>\n  \n  <!-- Красный куб - верхняя грань -->\n  <polygon points=\"16,32 24,24 40,24 32,32\" fill=\"#ff6666\" stroke=\"#cc3333\" stroke-width=\"1\"/>\n  \n  <!-- Красный куб - боковая грань -->\n  <polygon points=\"40,24 40,48 32,56 32,32\" fill=\"#cc3333\" stroke=\"#cc3333\" stroke-width=\"1\"/>\n  \n  <!-- Блики на кубе -->\n  <rect x=\"18\" y=\"34\" width=\"6\" height=\"6\" fill=\"#ff8888\" opacity=\"0.6\"/>\n  <polygon points=\"18,34 22,30 26,30 22,34\" fill=\"#ff8888\" opacity=\"0.4\"/>\n  \n  <!-- Тень -->\n  <ellipse cx=\"32\" cy=\"58\" rx=\"20\" ry=\"4\" fill=\"#000000\" opacity=\"0.3\"/>\n</svg>\n"),
}
